defaultPlacement: end
enableVersioning: true
handle: orders
name: Orders
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # English
    enabledByDefault: true
    hasUrls: true
    template: orders/_entry
    uriFormat: 'orders/{slug}'
type: channel
